import './style.scss'
import 'element-plus/theme-chalk/src/tabs.scss'
import 'element-plus/theme-chalk/src/tab-pane.scss'
import 'element-plus/theme-chalk/src/badge.scss'
import 'element-plus/theme-chalk/src/button.scss'
